export type ProgramCategory = 'production' | 'data' | 'quality' | 'creative' | 'operations';

export type Program = {
  category: ProgramCategory;
  en: { title: string; type: string; description: string };
  bn: { title: string; type: string; description: string };
};

export const programs: Program[] = [
  { category:'production', en:{title:'Print Plan Optimizer',type:'Production Planning',description:'Compares sheet, plate and print options and prepares a concise production plan.'}, bn:{title:'প্রিন্ট প্ল্যান অপটিমাইজার',type:'প্রোডাকশন প্ল্যানিং',description:'শিট, প্লেট ও প্রিন্টের বিকল্প তুলনা করে সংক্ষিপ্ত প্রোডাকশন প্ল্যান তৈরি করে।'} },
  { category:'production', en:{title:'Ratio Planning Engine',type:'Ratio & Capacity Planning',description:'Converts order data into ratio, repeat, sheet and plate planning outputs.'}, bn:{title:'রেশিও প্ল্যানিং ইঞ্জিন',type:'রেশিও ও ক্যাপাসিটি প্ল্যানিং',description:'অর্ডার ডাটা থেকে রেশিও, রিপিট, শিট ও প্লেট প্ল্যানিং আউটপুট তৈরি করে।'} },
  { category:'production', en:{title:'Secure Ratio Portal',type:'Controlled Web Workspace',description:'Provides a controlled browser workspace for ratio planning and authorized access.'}, bn:{title:'সিকিউর রেশিও পোর্টাল',type:'নিয়ন্ত্রিত ওয়েব ওয়ার্কস্পেস',description:'রেশিও প্ল্যানিং ও অনুমোদিত ব্যবহারের জন্য নিয়ন্ত্রিত ব্রাউজার ওয়ার্কস্পেস দেয়।'} },
  { category:'production', en:{title:'Offset Plate Composer',type:'Plate Production',description:'Matches order data with artwork and builds correctly sequenced production PDFs.'}, bn:{title:'অফসেট প্লেট কম্পোজার',type:'প্লেট প্রোডাকশন',description:'অর্ডার ডাটার সঙ্গে আর্টওয়ার্ক মিলিয়ে সঠিক ক্রমের প্রোডাকশন PDF তৈরি করে।'} },
  { category:'production', en:{title:'Combined Label Composer',type:'Print-ready Composition',description:'Assembles label blocks and prepares combined files for production output.'}, bn:{title:'কম্বাইন্ড লেবেল কম্পোজার',type:'প্রিন্ট-রেডি কম্পোজিশন',description:'লেবেল ব্লক সাজিয়ে প্রোডাকশন আউটপুটের জন্য কম্বাইন্ড ফাইল প্রস্তুত করে।'} },
  { category:'production', en:{title:'Buyer Layout Builder',type:'Buyer-specific Layout',description:'Maps buyer-specific elements into approved, repeatable production layouts.'}, bn:{title:'বায়ার লেআউট বিল্ডার',type:'বায়ার-ভিত্তিক লেআউট',description:'বায়ার-নির্দিষ্ট উপাদান অনুমোদিত ও পুনর্ব্যবহারযোগ্য প্রোডাকশন লেআউটে বসায়।'} },
  { category:'production', en:{title:'Care Layout Engine',type:'Care-label Layout',description:'Classifies source pages and composes fixed-format care-label layouts.'}, bn:{title:'কেয়ার লেআউট ইঞ্জিন',type:'কেয়ার-লেবেল লেআউট',description:'সোর্স পেজ শ্রেণিবিন্যাস করে নির্ধারিত ফরম্যাটের কেয়ার-লেবেল লেআউট তৈরি করে।'} },
  { category:'production', en:{title:'Price & Care Studio',type:'Multilingual Label Production',description:'Transforms order records into multilingual price and care-label artwork.'}, bn:{title:'প্রাইস অ্যান্ড কেয়ার স্টুডিও',type:'বহুভাষিক লেবেল প্রোডাকশন',description:'অর্ডার রেকর্ডকে বহুভাষিক প্রাইস ও কেয়ার-লেবেল আর্টওয়ার্কে রূপ দেয়।'} },
  { category:'production', en:{title:'Order Data Hub',type:'Order Production Control',description:'Consolidates order inputs, mappings and generated assets for production use.'}, bn:{title:'অর্ডার ডাটা হাব',type:'অর্ডার প্রোডাকশন কন্ট্রোল',description:'অর্ডার ইনপুট, ম্যাপিং ও তৈরি অ্যাসেট প্রোডাকশন ব্যবহারের জন্য একত্র করে।'} },

  { category:'data', en:{title:'Brand Data Uploader',type:'Database Intake',description:'Validates workbooks and prepares structured production database records.'}, bn:{title:'ব্র্যান্ড ডাটা আপলোডার',type:'ডাটাবেজ ইনটেক',description:'ওয়ার্কবুক যাচাই করে কাঠামোবদ্ধ প্রোডাকশন ডাটাবেজ রেকর্ড প্রস্তুত করে।'} },
  { category:'data', en:{title:'Label Data Hub',type:'Data Processing',description:'Classifies customer reports, validates records and updates production tables.'}, bn:{title:'লেবেল ডাটা হাব',type:'ডাটা প্রসেসিং',description:'কাস্টমার রিপোর্ট শ্রেণিবিন্যাস, রেকর্ড যাচাই এবং প্রোডাকশন টেবিল আপডেট করে।'} },
  { category:'data', en:{title:'Blister Workbook Builder',type:'Packaging Data',description:'Combines package, size and colour inputs into a production-ready workbook.'}, bn:{title:'ব্লিস্টার ওয়ার্কবুক বিল্ডার',type:'প্যাকেজিং ডাটা',description:'প্যাকেজ, সাইজ ও কালার ইনপুট একত্র করে প্রোডাকশন-রেডি ওয়ার্কবুক তৈরি করে।'} },
  { category:'data', en:{title:'Barcode Pair Processor',type:'Barcode Data Control',description:'Groups related barcode records and writes validated combined values.'}, bn:{title:'বারকোড পেয়ার প্রসেসর',type:'বারকোড ডাটা কন্ট্রোল',description:'সম্পর্কিত বারকোড রেকর্ড গ্রুপ করে যাচাইকৃত কম্বাইন্ড ভ্যালু তৈরি করে।'} },
  { category:'data', en:{title:'Barcode Workbook Joiner',type:'Workbook Automation',description:'Connects paired barcode data across structured workbook sheets.'}, bn:{title:'বারকোড ওয়ার্কবুক জয়নার',type:'ওয়ার্কবুক অটোমেশন',description:'কাঠামোবদ্ধ ওয়ার্কবুক শিটের মধ্যে সম্পর্কিত বারকোড ডাটা যুক্ত করে।'} },
  { category:'data', en:{title:'Serial Batch Fixer',type:'Sequence Correction',description:'Corrects serial order in controlled two- and three-item production batches.'}, bn:{title:'সিরিয়াল ব্যাচ ফিক্সার',type:'সিকোয়েন্স কারেকশন',description:'নিয়ন্ত্রিত দুই ও তিন আইটেমের প্রোডাকশন ব্যাচে সিরিয়ালের ক্রম ঠিক করে।'} },
  { category:'data', en:{title:'Order Sheet Extractor',type:'Structured Data Extraction',description:'Extracts selected order attributes into one consolidated workbook.'}, bn:{title:'অর্ডার শিট এক্সট্রাক্টর',type:'স্ট্রাকচার্ড ডাটা এক্সট্রাকশন',description:'নির্বাচিত অর্ডার তথ্য একটি সমন্বিত ওয়ার্কবুকে একত্র করে।'} },
  { category:'data', en:{title:'Batch QR Builder',type:'Variable Asset Generation',description:'Creates production-ready vector QR assets from spreadsheet rows.'}, bn:{title:'ব্যাচ QR বিল্ডার',type:'ভেরিয়েবল অ্যাসেট জেনারেশন',description:'স্প্রেডশিটের সারি থেকে প্রোডাকশন-রেডি ভেক্টর QR অ্যাসেট তৈরি করে।'} },
  { category:'data', en:{title:'Web Colour Lookup',type:'Reference Data Retrieval',description:'Reads approved colour mappings from an authorized browser session.'}, bn:{title:'ওয়েব কালার লুকআপ',type:'রেফারেন্স ডাটা রিট্রিভাল',description:'অনুমোদিত ব্রাউজার সেশন থেকে অনুমোদিত কালার ম্যাপিং সংগ্রহ করে।'} },
  { category:'data', en:{title:'Web Proof Bridge',type:'Reference Proof Workflow',description:'Collects authorized reference proofs and connects them to local review.'}, bn:{title:'ওয়েব প্রুফ ব্রিজ',type:'রেফারেন্স প্রুফ ওয়ার্কফ্লো',description:'অনুমোদিত রেফারেন্স প্রুফ সংগ্রহ করে লোকাল রিভিউর সঙ্গে যুক্ত করে।'} },
  { category:'data', en:{title:'Mail Layout Collector',type:'Mail Attachment Workflow',description:'Finds the latest matching layout attachments and sorts them by type.'}, bn:{title:'মেইল লেআউট কালেক্টর',type:'মেইল অ্যাটাচমেন্ট ওয়ার্কফ্লো',description:'সর্বশেষ মিল থাকা লেআউট অ্যাটাচমেন্ট খুঁজে ধরন অনুযায়ী সাজায়।'} },

  { category:'quality', en:{title:'Proof & Plate Inspector',type:'Prepress Quality Assurance',description:'Inspects artwork and production output and exports an evidence-based report.'}, bn:{title:'প্রুফ অ্যান্ড প্লেট ইন্সপেক্টর',type:'প্রি-প্রেস কোয়ালিটি অ্যাস্যুরেন্স',description:'আর্টওয়ার্ক ও প্রোডাকশন আউটপুট যাচাই করে প্রমাণভিত্তিক রিপোর্ট তৈরি করে।'} },
  { category:'quality', en:{title:'Brand Proof Inspector',type:'Brand-specific Validation',description:'Applies focused content, barcode and geometry checks to brand workflows.'}, bn:{title:'ব্র্যান্ড প্রুফ ইন্সপেক্টর',type:'ব্র্যান্ড-নির্দিষ্ট ভ্যালিডেশন',description:'ব্র্যান্ড ওয়ার্কফ্লোতে প্রয়োজনীয় কনটেন্ট, বারকোড ও জ্যামিতিক যাচাই চালায়।'} },
  { category:'quality', en:{title:'PDF Batch Processor',type:'Batch Document Utility',description:'Prepares multiple PDF files through a controlled batch workflow.'}, bn:{title:'PDF ব্যাচ প্রসেসর',type:'ব্যাচ ডকুমেন্ট ইউটিলিটি',description:'নিয়ন্ত্রিত ব্যাচ ওয়ার্কফ্লোর মাধ্যমে একাধিক PDF ফাইল প্রস্তুত করে।'} },
  { category:'quality', en:{title:'Mono PDF Converter',type:'Colour Conversion',description:'Converts colour PDF content into production-ready grayscale output.'}, bn:{title:'মনো PDF কনভার্টার',type:'কালার কনভার্সন',description:'কালার PDF কনটেন্টকে প্রোডাকশন-রেডি গ্রেস্কেল আউটপুটে রূপ দেয়।'} },
  { category:'quality', en:{title:'Page Set Splitter',type:'Page Separation',description:'Separates even and odd page sets across a batch of documents.'}, bn:{title:'পেজ সেট স্প্লিটার',type:'পেজ সেপারেশন',description:'এক ব্যাচ ডকুমেন্টের জোড় ও বিজোড় পেজ সেট আলাদা করে।'} },
  { category:'quality', en:{title:'PDF Page Prep',type:'Page Preparation',description:'Creates first-page, even-page and odd-page outputs for each file.'}, bn:{title:'PDF পেজ প্রেপ',type:'পেজ প্রিপারেশন',description:'প্রতিটি ফাইলের প্রথম, জোড় ও বিজোড় পেজের আলাদা আউটপুট তৈরি করে।'} },
  { category:'quality', en:{title:'First-page Grouper',type:'Document Grouping',description:'Keeps selected opening pages and combines files belonging to one set.'}, bn:{title:'ফার্স্ট-পেজ গ্রুপার',type:'ডকুমেন্ট গ্রুপিং',description:'নির্বাচিত প্রথম পেজ রেখে একই সেটের ফাইলগুলো একত্র করে।'} },
  { category:'quality', en:{title:'Layout Cleaner',type:'Production Cleanup',description:'Removes selected page artifacts while preserving essential image content.'}, bn:{title:'লেআউট ক্লিনার',type:'প্রোডাকশন ক্লিনআপ',description:'প্রয়োজনীয় ইমেজ কনটেন্ট রেখে নির্বাচিত পেজ আর্টিফ্যাক্ট সরায়।'} },
  { category:'quality', en:{title:'Header/Footer Redactor',type:'Permanent Information Removal',description:'Permanently removes configured header and footer information from documents.'}, bn:{title:'হেডার/ফুটার রিড্যাক্টর',type:'স্থায়ী তথ্য অপসারণ',description:'ডকুমেন্ট থেকে নির্ধারিত হেডার ও ফুটারের তথ্য স্থায়ীভাবে সরায়।'} },
  { category:'quality', en:{title:'Page Colour Classifier',type:'Visual Page Detection',description:'Detects a target page characteristic and labels files by result.'}, bn:{title:'পেজ কালার ক্লাসিফায়ার',type:'ভিজুয়াল পেজ ডিটেকশন',description:'নির্দিষ্ট পেজ বৈশিষ্ট্য শনাক্ত করে ফলাফল অনুযায়ী ফাইল চিহ্নিত করে।'} },
  { category:'quality', en:{title:'Mark Replacement Tool',type:'PDF Asset Correction',description:'Replaces a designated mark consistently across document pages.'}, bn:{title:'মার্ক রিপ্লেসমেন্ট টুল',type:'PDF অ্যাসেট কারেকশন',description:'ডকুমেন্টের পেজজুড়ে নির্দিষ্ট মার্ক ধারাবাহিকভাবে প্রতিস্থাপন করে।'} },

  { category:'creative', en:{title:'Asset Merge Studio',type:'Template Asset Automation',description:'Places linked artwork and supporting data into controlled layout slots.'}, bn:{title:'অ্যাসেট মার্জ স্টুডিও',type:'টেমপ্লেট অ্যাসেট অটোমেশন',description:'নিয়ন্ত্রিত লেআউট স্লটে লিংক করা আর্টওয়ার্ক ও সহায়ক ডাটা বসায়।'} },
  { category:'creative', en:{title:'Data Merge Studio',type:'Variable Data Artwork',description:'Populates numbered artwork placeholders and prepares multi-page output.'}, bn:{title:'ডাটা মার্জ স্টুডিও',type:'ভেরিয়েবল ডাটা আর্টওয়ার্ক',description:'নাম্বার করা আর্টওয়ার্ক প্লেসহোল্ডার পূরণ করে মাল্টি-পেজ আউটপুট প্রস্তুত করে।'} },
  { category:'creative', en:{title:'Fusion Plate Builder',type:'Integrated Artwork Workflow',description:'Combines data, assets and page grouping in one production workflow.'}, bn:{title:'ফিউশন প্লেট বিল্ডার',type:'ইন্টিগ্রেটেড আর্টওয়ার্ক ওয়ার্কফ্লো',description:'ডাটা, অ্যাসেট ও পেজ গ্রুপিং একটি প্রোডাকশন ওয়ার্কফ্লোতে একত্র করে।'} },
  { category:'creative', en:{title:'Link Refresh',type:'Artwork Relinking',description:'Refreshes placed artwork by matching approved replacement file names.'}, bn:{title:'লিংক রিফ্রেশ',type:'আর্টওয়ার্ক রিলিংকিং',description:'অনুমোদিত replacement filename মিলিয়ে placed artwork রিফ্রেশ করে।'} },
  { category:'creative', en:{title:'Selection Artboard Builder',type:'Artboard Automation',description:'Converts selected layout areas into correctly ordered artboards.'}, bn:{title:'সিলেকশন আর্টবোর্ড বিল্ডার',type:'আর্টবোর্ড অটোমেশন',description:'নির্বাচিত লেআউট এরিয়াকে সঠিক ক্রমে আর্টবোর্ডে রূপ দেয়।'} },

  { category:'operations', en:{title:'Order File Organizer',type:'File Operations',description:'Groups production files into folders using order identifiers.'}, bn:{title:'অর্ডার ফাইল অর্গানাইজার',type:'ফাইল অপারেশনস',description:'অর্ডার আইডেন্টিফায়ার ব্যবহার করে প্রোডাকশন ফাইল ফোল্ডারে গ্রুপ করে।'} },
  { category:'operations', en:{title:'Database Repair Console',type:'Database Maintenance',description:'Repairs selected table names and saved-query references.'}, bn:{title:'ডাটাবেজ রিপেয়ার কনসোল',type:'ডাটাবেজ মেইনটেন্যান্স',description:'নির্বাচিত টেবিলের নাম ও saved-query reference মেরামত করে।'} },
  { category:'operations', en:{title:'Database Link Diagnostic',type:'Connectivity Testing',description:'Verifies database driver availability and connection readiness.'}, bn:{title:'ডাটাবেজ লিংক ডায়াগনস্টিক',type:'কানেক্টিভিটি টেস্টিং',description:'ডাটাবেজ ড্রাইভারের উপস্থিতি ও কানেকশন প্রস্তুতি যাচাই করে।'} },
  { category:'operations', en:{title:'License Console',type:'Product Access Control',description:'Generates signed, product-specific license files for controlled deployment.'}, bn:{title:'লাইসেন্স কনসোল',type:'প্রোডাক্ট অ্যাক্সেস কন্ট্রোল',description:'নিয়ন্ত্রিত ডেপ্লয়মেন্টের জন্য signed product-specific license file তৈরি করে।'} },
  { category:'operations', en:{title:'Local Tool Gateway',type:'Internal Utility Access',description:'Opens selected internal utilities from a local control page.'}, bn:{title:'লোকাল টুল গেটওয়ে',type:'ইন্টারনাল ইউটিলিটি অ্যাক্সেস',description:'লোকাল কন্ট্রোল পেজ থেকে নির্বাচিত ইন্টারনাল ইউটিলিটি চালু করে।'} },
  { category:'operations', en:{title:'Runtime Setup Assistant',type:'Environment Setup',description:'Prepares required software packages for supported tool environments.'}, bn:{title:'রানটাইম সেটআপ অ্যাসিস্ট্যান্ট',type:'এনভায়রনমেন্ট সেটআপ',description:'সমর্থিত টুল এনভায়রনমেন্টের জন্য প্রয়োজনীয় সফটওয়্যার প্যাকেজ প্রস্তুত করে।'} },
  { category:'operations', en:{title:'Guide Publisher',type:'Technical Documentation',description:'Transforms prepared guidance into consistent branded documentation.'}, bn:{title:'গাইড পাবলিশার',type:'টেকনিক্যাল ডকুমেন্টেশন',description:'প্রস্তুত গাইডকে সামঞ্জস্যপূর্ণ ব্র্যান্ডেড ডকুমেন্টেশনে রূপ দেয়।'} },
  { category:'operations', en:{title:'Proposal Publisher',type:'Business Document Production',description:'Produces a polished branded proposal from prepared business content.'}, bn:{title:'প্রপোজাল পাবলিশার',type:'বিজনেস ডকুমেন্ট প্রোডাকশন',description:'প্রস্তুত বিজনেস কনটেন্ট থেকে পরিপাটি ব্র্যান্ডেড প্রপোজাল তৈরি করে।'} },
  { category:'operations', en:{title:'Brand Asset Renderer',type:'Brand Asset Production',description:'Converts an approved vector mark into reusable raster assets.'}, bn:{title:'ব্র্যান্ড অ্যাসেট রেন্ডারার',type:'ব্র্যান্ড অ্যাসেট প্রোডাকশন',description:'অনুমোদিত ভেক্টর মার্ককে পুনর্ব্যবহারযোগ্য রাস্টার অ্যাসেটে রূপ দেয়।'} },
];

export const categoryOrder: Array<'all' | ProgramCategory> = ['all','production','data','quality','creative','operations'];

export const categoryLabels = {
  en: { all:'All workflows', production:'Production & Planning', data:'Data & Labels', quality:'Quality & PDF', creative:'Creative Automation', operations:'Operations & Support' },
  bn: { all:'সব ওয়ার্কফ্লো', production:'প্রোডাকশন ও প্ল্যানিং', data:'ডাটা ও লেবেল', quality:'কোয়ালিটি ও PDF', creative:'ক্রিয়েটিভ অটোমেশন', operations:'অপারেশনস ও সাপোর্ট' },
};
